<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Implements hook_preprocess_paragraph().
 *
 * Adding event search form into paragraph.
 */
function os2web_events_preprocess_paragraph__os2web_events_search(&$variables) {
  $variables['content'] = views_embed_view('os2web_events_search', 'os2web_events_embed_search');
}